### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by alanshaw**

### CODE REVIEW

**Comment by achingbrain** [comment]
This has pulled in `peer-id@0.13.x` which breaks `js-ipfs` with this sort of error:

```
Uncaught TypeError: callback is not a function
      at /foo/js-ipfs/node_modules/libp2p-crypto/src/keys/rsa-class.js:124:7
      at /foo/js-ipfs/node_modules/libp2p-crypto/node_modules/multihashing-async/src/index.js:33:5
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This is because `js-ipfs` depends on `peer-id@0.12.x` which is has to until `js-libp2p` upgrades otherwise you can't dial anyone.

**Comment by achingbrain** [comment]
I should say, it breaks because this went out as a patch release.  Could it (or at least the peer-id upgrade) be reverted, a new patch release done and then this re-merged and released as a minor?

**Comment by jacobheun** [comment]
`libp2p-crypto` is the issue, that's a breaking change, as well as the `interface-datastore`. `peer-id` is a dev dependency.

@vasco-santos can we do a revert patch release and then a minor release with this change?

**Comment by vasco-santos** [comment]
oh, on it

**Comment by vasco-santos** [comment]
Released `0.6.0`

**Pull request merged**
