### PR TITLE
use libp2p-crypto

### PR DESCRIPTION
**Pull request by richardschneider**
Remove `node-forge` dependency, #7

### CODE REVIEW

**Comment by diasdavid** [comment]
released libp2p-crypto ⚡️

**Comment by richardschneider** [comment]
@diasdavid Thanks for libp2p-crypto release.  just waiting on https://github.com/libp2p/js-peer-id/pull/73, then I can remove WIP and you can review.

**Comment by richardschneider** [comment]
@diasdavid There are 37 tests and I think the code coverage is good. 

Please tell me what is required for the 2nd iteration.

**Comment by richardschneider** [comment]
@diasdavid Please read the [entire keychain.spec](https://github.com/libp2p/js-libp2p-keychain/blob/e48cf2dbfa42eb4c60d6b31d75e2e2c8cc6cd6dd/test/keychain.spec.js) not the diff.

**Comment by diasdavid** [comment]
As said, looks good now :) Thanks for creating this ❤️

**Pull request merged**
